#Define how to docker containers should run and scale services
version: "3"
services:
  helloworld:
    # replace username/repo:tag with your name and image details
    image: crkatz/helloworld:1.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:5000"
    networks:
      - webnet
networks:
  webnet:
